### ISSUE TITLE
Use Backed for every customElement

### ISSUE THREAD

**Issue by VandeurenGlenn** [Reeflight/Reeflight#10]
Doing this enables us to run our app in a node-environment

**Comment by AndrewVanardennen** [comment]
Ok

Op 11 mrt. 2017 23:38 schreef "Glenn Vandeuren" <notifications@github.com>:

**Comment by VandeurenGlenn** [comment]
@AndrewVanardennen I think it was this one

**Comment by VandeurenGlenn** [comment]
## Progress
- 72f437bad4129e3bd4aa8f3b4b820f2a23a350a2

**Comment by VandeurenGlenn** [comment]
## TODO
- fix pubsubs

**Comment by VandeurenGlenn** [comment]
Closing this since Backed is stable & code ported....
