### ISSUE TITLE
backed build issue

### ISSUE THREAD

**Issue by AndrewVanardennen** [Reeflight/Reeflight#13]
![image](https://cloud.githubusercontent.com/assets/6136142/25954853/c0133f16-3667-11e7-807d-b97233567264.png)

**Comment by VandeurenGlenn** [comment]
When did the error ocurre? did you started from scratch or synced the code with github?

**Comment by AndrewVanardennen** [comment]
started from scratch. Did npm i and updated back-cli.

**Comment by VandeurenGlenn** [comment]
Ok, I'm doing the same, was it on linux or window?

**Comment by AndrewVanardennen** [comment]
It's on a windows 7 64bit;

**Comment by VandeurenGlenn** [comment]
Strange, have you tried yarn upgrade already?

**Comment by AndrewVanardennen** [comment]
I don't have yarn installed. Did a npm i.

**Comment by VandeurenGlenn** [comment]
Updating Node should fix it, the error comes from the cli itself I suspect it has to do with the async await generator

**Comment by AndrewVanardennen** [comment]
Is it a prerequisite to install it?

**Comment by AndrewVanardennen** [comment]
I'll update node.

**Comment by VandeurenGlenn** [comment]
Remeber to install using the global flag [-g]

**Comment by AndrewVanardennen** [comment]
What do I need to install with the global flag?

**Comment by VandeurenGlenn** [comment]
there is something wrong with the distributed package, propbably babel didn't transpile the generator

**Comment by VandeurenGlenn** [comment]
Yarn

**Comment by AndrewVanardennen** [comment]
Installed it with the .msi installer.

**Comment by AndrewVanardennen** [comment]
Still getting the same error after updating node and installing yarn.

**Comment by VandeurenGlenn** [comment]
And you are on node 7?

**Comment by AndrewVanardennen** [comment]
yes, 7.10.0.

**Comment by AndrewVanardennen** [comment]
Can be closed. There were problems with node and npm.
